services:
  syncinator:
    container_name: obsidian-live-syncinator-server 
    image: ghcr.io/hiimjako/obsidian-live-syncinator-server:main
    environment:
      - JWT_SECRET=secret
      - SQLITE_FILEPATH=./data/db.sqlite3
    ports:
      - 8080:8080
