name: JavaScript Lint & Test
concurrency:
  group: ${{github.repository}}-${{ github.ref_name }}-javascript
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.filter.outputs.js == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            js:
              - '**/*.ts'
              - '**/*.js'
  lint-and-test:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.files_changed == 'true' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
    
      - name: Install dependencies
        run: npm ci
    
      - name: Lint
        run: |
          npm run lint
          npm run format
      
      - name: Run tests
        run: npm run ci-test
